In [1]:
import torch
from IPython.display import display
torch.set_default_device("cuda")
torch.set_default_dtype(torch.float64)

In [2]:
x = torch.randn(3, 2, requires_grad=True)
x_ind = torch.randn(4, 2, requires_grad=True)
x_all = torch.randn(5, 2, requires_grad=True)
y_all = torch.randn(5, requires_grad=True)
l = torch.rand(2, requires_grad=True)

out = ((x[:, None] - x_ind[None]) / l).sum(-1) @ ((x_ind[:, None] - x_all[None]) / l).sum(-1) @ y_all

display(
	(((x_ind[:, None] - x_all[None]) / l).sum(-1) @ y_all).sum() / l,
	torch.autograd.grad(out, x, torch.ones_like(out), True, False, True, True, False, True)[0].detach(),
	torch.autograd.grad(out, x_ind, torch.eye(out.numel()), True, False, True, True, True, True)[0].detach().reshape(out.shape + x_ind.shape),
	torch.autograd.grad(out, x_all, torch.eye(out.numel()), True, False, True, True, True, True)[0].detach().reshape(out.shape + x_all.shape),
	torch.autograd.grad(out, y_all, torch.eye(out.numel()), True, False, True, True, True, True)[0].detach().reshape(out.shape + y_all.shape),
	torch.autograd.grad(out, l, torch.eye(out.numel()), True, False, True, True, True, True)[0].detach().reshape(out.shape + l.shape),
	-((x[:, None] - x_ind[None]) / l**2).sum(-1) @ ((x_ind[:, None] - x_all[None]) / l).sum(-1) @ y_all - ((x[:, None] - x_ind[None]) / l).sum(-1) @ ((x_ind[:, None] - x_all[None]) / l**2).sum(-1) @ y_all
)

tensor([ 6.4920, 13.9682], device='cuda:0', grad_fn=<DivBackward0>)

tensor([[ 6.4920, 13.9682],
        [ 6.4920, 13.9682],
        [ 6.4920, 13.9682]], device='cuda:0')

tensor([[[ 14.2293,  30.6158],
         [  4.3619,   9.3852],
         [ 13.3705,  28.7681],
         [ -9.8274, -21.1447]],

        [[  4.9535,  10.6580],
         [ -4.9139, -10.5727],
         [  4.0947,   8.8103],
         [-19.1032, -41.1025]],

        [[  3.8796,   8.3474],
         [ -5.9878, -12.8833],
         [  3.0208,   6.4997],
         [-20.1771, -43.4131]]], device='cuda:0')

tensor([[[-30.5108, -65.6472],
         [-13.7985, -29.6888],
         [ 15.2127,  32.7318],
         [-10.9610, -23.5837],
         [ 11.4312,  24.5954]],

        [[  9.0349,  19.4394],
         [  4.0860,   8.7914],
         [ -4.5048,  -9.6925],
         [  3.2458,   6.9836],
         [ -3.3850,  -7.2832]],

        [[ 13.6132,  29.2902],
         [  6.1566,  13.2465],
         [ -6.7876, -14.6042],
         [  4.8905,  10.5225],
         [ -5.1003, -10.9739]]], device='cuda:0')

tensor([[  8.9424, -37.4357, -85.7541, -66.4505,  66.1929],
        [-40.7867, -27.0533, -12.7452, -18.4614, -57.7397],
        [-46.5441, -25.8512,  -4.2927, -12.9055, -72.0879]], device='cuda:0')

tensor([[ -57.5943,   10.1988],
        [ -14.8793, -227.0059],
        [ -20.5788, -231.5648]], device='cuda:0')

tensor([ -47.3955, -241.8853, -252.1436], device='cuda:0',
       grad_fn=<SubBackward0>)