In [1]:
import torch

torch.manual_seed(0)
torch.set_default_dtype(torch.double)

In [2]:
n = int(torch.randint(10, 20, (1,)).item())
n

14

In [3]:
coe = torch.randint(0, 10, (n,))
values = torch.tensor([[10, 5], [2, 1]])
print(coe, values, sep="\n")

tensor([9, 3, 0, 3, 9, 7, 3, 7, 3, 1, 6, 6, 9, 8])
tensor([[10,  5],
        [ 2,  1]])


In [4]:
print("exact value:")
exact = sum((coe[i] * values ** i for i in range(n)), start=torch.zeros_like(values))
print(exact)

exact value:
tensor([[89661373793039,    12318199774],
        [        123607,             74]])


In [5]:
print("Horner's scheme:")
result = torch.full_like(values, coe[-1].item())
for i in range(n - 2, -1, -1):
	result = values * result + coe[i]
print(result, torch.abs(result - exact).sum().item(), sep="\n")

Horner's scheme:
tensor([[89661373793039,    12318199774],
        [        123607,             74]])
0


In [6]:
print("Estrin's scheme:")
result = coe[:, *([torch.newaxis] * values.ndim)] * torch.ones_like(values)
n = coe.shape[0] - 1
pow = values
while n > 0:
	print(result[:, 0, 0], n)
	for i in range(0, n, 2):
		result[i//2] = result[i] + result[i+1] * pow
	if n % 2 == 0:
		result[n//2] = result[n]
	pow = pow * pow
	n //= 2
print(result[0], torch.abs(result[0] - exact).sum().item(), sep="\n")

Estrin's scheme:
tensor([9, 3, 0, 3, 9, 7, 3, 7, 3, 1, 6, 6, 9, 8]) 13
tensor([39, 30, 79, 73, 13, 66, 89,  7,  3,  1,  6,  6,  9,  8]) 6
tensor([3039, 7379, 6613,   89,   13,   66,   89,    7,    3,    1,    6,    6,
           9,    8]) 3
tensor([73793039,   896613,     6613,       89,       13,       66,       89,
               7,        3,        1,        6,        6,        9,        8]) 1
tensor([[89661373793039,    12318199774],
        [        123607,             74]])
0
